name: pip_services3_components
version: 1.0.0
author: Sergey Seroukhov <seroukhov@gmail.com>
description: Components patterns for Pip.Services in Dart
homepage: https://github.com/pip-services3-dart/pip-services3-components-dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  pip_services3_commons: "^1.0.0"
  handlebars2: ^0.0.3
  yaml: ^2.2.0
  sprintf: "^4.0.0"

dev_dependencies:
  test: '>=1.14.2 <2.0.0'